### ISSUE TITLE
Moving code that worked on Python3.4 to Python3.7 breaks authontication

### ISSUE THREAD

**Issue by rbarakjsonar** [nithinmurali/pygsheets#349]
Note, if this is a usage question, please ask a question in stackoverflow with `pygsheets` tag.

**Describe the bug**
I have code that relies on pygsheets.
It works on Python3.4
I need to run it on a machine with Python3.7
The code breaks with:
AttributeError: 'Client' object has no attribute 'list_ssheets' 

**To Reproduce**

$ python AttributeError_demo.py 
Traceback (most recent call last):
  File "AttributeError_demo.py", line 13, in <module>
    outh_file = '/home/qa/.aws/client_secret.json')
  File "AttributeError_demo.py", line 6, in create_spreadsheet
    client.list_ssheets(parent_id=None)
AttributeError: 'Client' object has no attribute 'list_ssheets'

```
import pygsheets
def create_spreadsheet(outh_file, spreadsheet_name = "jSonar AWS usage"):
    client = pygsheets.authorize(outh_file=outh_file, outh_nonlocal=True)
    client.list_ssheets(parent_id=None)
    spread_sheet = client.create(spreadsheet_name)
    return spread_sheet
if __name__ == "__main__":
    spread_sheet = create_spreadsheet(spreadsheet_name = "jSonar AWS usage",
                                                            outh_file = '/home/qa/.aws/client_secret.json')

# see error: AttributeError: 'Client' object has no attribute 'list_ssheets'
```

**System Information**
 - OS: Red Hat Enterprise Linux 7.4
- Python version: 
$ python -V
Python 3.7.3

 - pygsheets version :
$ python -c "import pygsheets ; import requests ; print(requests.__version__)"
2.22.0
$ pip3.7 list | grep pygsheets
pygsheets                2.0.1   
$ pip3.7 freeze | grep pygsheets
pygsheets==2.0.1

**Comment by nithinmurali** [comment]
I think while changing python version you installed the pyghseets 2.x while earlier you were using pygsheets 1.x . That's the reason why your code is breaking. Either update code to 2.x or use 1.x.
