### ISSUE TITLE
object has no attribute 'before_request'

### ISSUE THREAD

**Issue by robsgithub** [nithinmurali/pygsheets#311]

**Comment by robsgithub** [comment]
Ran into a "object has no attribute 'before_request" in the google_auth_httplib module after upgrading from v1.1.4.  I had been creating credentials using ServiceAccountCredentials.from_json_keyfile_name function.

I resolved by just passing credential file path to the service_file flag 
ie
pygsheets.authorize(service_file="/my/path/to/file.json")

**Comment by robsgithub** [comment]
As mentioned before i found a workaround
